### ISSUE TITLE
Destructuring or establishing more concise variable name for  incoming props  in Reviewer.jsx

### ISSUE THREAD

**Issue by KKranzfelder** [The-Hanging-Gardens-of-Babylon/The-Gardens#56]
https://github.com/The-Hanging-Gardens-of-Babylon/The-Gardens/blob/fd06e36b10145e15935a031a436a38a8412c5c29/client/src/components/Ratings_Reviews/components/Reviewer.jsx#L6

#Description
Having to type prop.[propname] repeatedly creates an unnecessary inflation of text. If the props are destuctured  in the component's initialization, you can avoid this. Alternatively, creating a variable that points to a specific prop that is more concise will also serve a similar function.

##File
client/src/components/Ratings_Reviews/components/Reviewer.jsx

##Tasks

Destructure Method:

- [ ] Destructure the props needed for the component on initialization for easier referencing experience.
- [ ] Multiedit the calls to that prop to now use the updated reference syntax.

Variable Initialization Method:

- [ ] Similar to Destructure but instead intialize a consice, descriptive variable that references that prop.
- [ ] Update the corresponding prop references to the new variable name.
